import type { Metadata } from "next";
import "./assets/styles/styles.scss";
import Footer from "./components/Layout/Footer";
import Header from "./components/Layout/Header";

export const metadata: Metadata = {
  title: "20250120 ENTEST 최일권",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: Readonly<{ children: React.ReactNode }>) => {
  return (
    <html lang="kr">
      <body className="c_body">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
